### ISSUE TITLE
permissions/ownership of logcheck.conf

### ISSUE THREAD

**Issue by stephankn** [Oefenweb/ansible-logcheck#7]
/etc/logcheck/logcheck.conf is created as `0644` with group `root`. Directly installing on Ubuntu creates this with the better looking permissions `0640` and group `logcheck` similar the other configuration files.

I see no reason to have the config world-readable so suggesting to fix it. Also group should be `logcheck` so file can be read by the process later on.

**Comment by tersmitten** [comment]
What does the installer do by default?

**Comment by stephankn** [comment]
Checked with Ubuntu 14.04 LTS (trusty) and 16.04 LTS (xenial). In both distributions the package installs logcheck.conf with permissions 0640 and group logcheck. This patch fixed what I consider a bug in this ansible script. As the script deploys the file with group root, later the logcheck process (started as user logcheck) would not be able to read the config. So the config had to be world-readable. 
Having it controlled by group permissions makes much more sense from a security POV.

**Comment by tersmitten** [comment]
Fixed in #8
